Some missing type annotations added

diff --git a/hooks/pre-push b/hooks/pre-push
--- a/hooks/pre-push
+++ b/hooks/pre-push
@@ -1,4 +1,11 @@
 #!/bin/bash
+echo "✅ Static analysis"
+ruff check .
+status=$?
+if [ $status -ne 0 ]; then
+  echo "❌ Static analysis failed, push aborted."
+  exit $status
+fi
 echo "🧪 Running tests before push..."
 pytest --quiet
 status=$?
